### ISSUE TITLE
Doesn't render in Workflowy App

### ISSUE THREAD

**Issue by hueykwik** [wonglkd/mathflowy#2]
Mathflowy works when I'm viewing Workflowy in Chrome, but not when I'm using the Workflowy Chrome App. Is there a way to get it working in the Chrome App?

**Comment by wonglkd** [comment]
From what I've read, this (injecting content scripts into Chrome extensions) isn't allowed by Chrome - see https://github.com/thricedotted/mathflowy/issues/4 and this [stackoverflow answer](http://stackoverflow.com/questions/10196258/does-content-scripts-matches-chrome-extension-work/10196428#10196428). If you can find a way to do so, I'll love to know. Thanks!
