### ISSUE TITLE
Will mathflowy still work when the MathJax CDN shuts down?

### ISSUE THREAD

**Issue by elizhenning** [wonglkd/mathflowy#5]
Hi Daniel, is mathflowy still going to work after April 30 when MathJax shuts down its CDN? Where are you calling the rendering? Thanks!

**Comment by wonglkd** [comment]
Hi Elizabeth: good catch, thanks for pointing that out! I'll update the plugin accordingly to point to another CDN. Cheers!

**Comment by elizhenning** [comment]
Glad to hear it! I love mathflowy, keep up the great work!

**Comment by wonglkd** [comment]
Hi Elizabeth: I've updated it and pushed it to the Chrome store. Let me know if you find any issues. It's really thricedotted's plugin - I'm just helping to keep it up to date. Glad you like it!
